name: Zip Directory

on:
  push:
    paths:
      - 'templates/**'

jobs:
  job1:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'templates/contracts/erc721/**')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: test echo
        run: echo "hello world"

      # - name: Zip the directory
      #   run: zip -r erc721.zip templates/contracts/erc721/

      # - name: Upload ZIP as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: templates/zips
      #     path: erc721.zip
